backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: /site/assets/images/uploads
public_folder: "/assets/images/uploads"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "AOT Pages"
    name: aot-pages
    files:
      - name: "aot-home"
        label: "AOT of Things Home"
        file: "site/aot/home.json"
        fields:
          - label: Name
            name: name
            widget: string
          - label: Description
            name: description
            widget: markdown
          - label: Projects
            name: projects
            widget: list
            fields: 
              - label: Title
                name: title 
                widget: string
              - label: Content
                name: content
                widget: markdown
              - label: Image
                name: image
                widget: image
              - label: "Details Link"
                name: detailsLink
                widget: string
          - label: "Home Spread"
            name: homeSpread
            widget: list
            fields:
              - label: Image
                name: image
                widget: image
          - label: "Small Image"
            name: smallImage
            widget: image
  - label: "AOT e911 Page"
    name: aot-e911-page
    folder: "site/aot/pages/e911"
    format: json
    create: true
    fields:
      - label: Slug
        name: slug
        widget: string
      - label: Title
        name: title
        widget: string
      - label: Sections
        name: sections
        widget: list 
        fields:
          - label: Title
            name: title
            widget: string
            required: false
          - label: Content
            name: content
            widget: markdown
            required: false
          - label: Image
            name: image
            widget: image
            required: false
      - label: "Sort Code"
        name: sortCode
        widget: number
      - label: "Related Links"
        name: relatedLinks
        widget: list
        fields:
          - label: Caption
            name: caption
            widget: string
          - label: Link
            name: link
            widget: string
        required: false
  - label: "AOT GynoSMART Page"
    name: aot-gs-page
    folder: "site/aot/pages/gs"
    create: true
    format: json
    slug: "{{slug}}_{{day}}_{{month}}_{{year}}"
    fields:
      - label: Slug
        name: slug
        widget: string
      - label: Title
        name: title
        widget: string
      - label: Sections
        name: sections
        widget: list 
        fields:
          - label: Title
            name: title
            widget: string
            required: false
          - label: Content
            name: content
            widget: markdown
            required: false
          - label: Image
            name: image
            widget: image
            required: false
      - label: "Sort Code"
        name: sortCode
        widget: number
      - label: "Related Links"
        name: relatedLinks
        widget: list
        fields:
          - label: Caption
            name: caption
            widget: string
          - label: Link
            name: link
            widget: string
        required: false
  - label: "Age Based Health Notification"
    name: clx-abh-info
    folder: "site/notifications/clx-abh"
    create: true
    format: json
    slug: '{{day}}_{{month}}_{{year}}_{{hour}}{{minute}}{{second}}'
    fields:
      - label: Age
        widget: number
        name: age
      - label: "Age's Unit"
        widget: select
        name: ageUnit
        options: ['Months', 'Years']
      - label: Domain
        widget: select
        name: domain
        options: ['Child Health', 'Maternal', 'General Preventive Health', 'Environmental Health', 'Infectious Disease', 'Health Screening']
      - label: Content
        widget: markdown
        name: content
      - label: Image
        widget: image
        name: image
        required: false
      - label: Title
        widget: string
        name: title
        required: false
        default: 'just-ignore'